# Generated by Django 4.1.1 on 2022-10-14 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Club", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_name", models.CharField(max_length=50)),
                ("breif", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_id", models.CharField(max_length=20)),
                ("photo", models.ImageField(upload_to="pics")),
            ],
        ),
        migrations.CreateModel(
            name="ClubImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("photo", models.ImageField(upload_to="pics")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Club.clubs"
                    ),
                ),
            ],
        ),
    ]
